name: lint && tests
on:
  push:
  pull_request:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: fmt
        run: gofmt -l -w $(find . -type f -name '*.go')

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48
          skip-build-cache: true

      - name: test
        run: go test -cover ./...
